# Generated by Django 6.0.6 on 2026-07-06 10:53

import django.db.models.deletion
import dsr.models
import dsr.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DSRDailySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsr_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('purpose_of_visit', models.CharField(choices=[('INSTALLATION', 'Installation'), ('SERVICE', 'Service'), ('INSPECTION', 'Inspection'), ('AMC', 'AMC'), ('MEETING', 'Meeting'), ('SURVEY', 'Survey'), ('OTHER', 'Other')], max_length=20)),
                ('client_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('project_name', models.CharField(max_length=200)),
                ('project_address', models.TextField()),
                ('google_maps_link', models.URLField(blank=True)),
                ('project_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('HOSPITAL', 'Hospital'), ('SCHOOL_COLLEGE', 'School/College'), ('HOTEL', 'Hotel'), ('OFFICE', 'Office'), ('FACTORY', 'Factory'), ('WAREHOUSE', 'Warehouse'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], max_length=20)),
                ('building_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10)),
                ('built_up_area', models.CharField(blank=True, max_length=50)),
                ('project_stage', models.CharField(choices=[('NEW_CONSTRUCTION', 'New Construction'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('EXISTING_BUILDING', 'Existing Building'), ('RENOVATION', 'Renovation')], max_length=20)),
                ('work_done', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dsrs', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsrs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DSRAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=dsr.models.dsr_attachment_upload_path, validators=[dsr.validators.validate_dsr_attachment])),
                ('original_filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PROJECT_PHOTO', 'Project Photo'), ('ATTACHMENT', 'Attachment')], default='ATTACHMENT', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dsr.dsr')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dsr',
            index=models.Index(fields=['status'], name='dsr_dsr_status_914fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='dsr',
            index=models.Index(fields=['visit_date'], name='dsr_dsr_visit_d_83e84e_idx'),
        ),
    ]
